[package]
name = "container-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1"

libc = "0.2"
uuid = { version = "1", features = ["v4", "fast-rng"] }

log = "0.4"
fern = "0.6"
chrono = "0.4"